remote_theme: pages-themes/minimal@v0.2.0

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Amelia J. Cordwell
logo: /assets/img/logo.png
show_downloads: false
google_analytics: false

description: |
   I am an an astrophysics PhD student in the Astrophysical Fluid Dynamics group at 
   the Department of Applied Mathematics and Theoretical Physics at the University of Cambridge.

   My supervisor is Roman R. Rafikov, and I can be contacted at ajc356@cam.ac.uk.

   I presently looking for postdoctoral positions to start in October 2026.
